version: '3.9'
services:
  elasticsearch:
    build: elasticsearch/
    hostname: crypto-tracker_elasticsearch
    container_name: crypto-tracker_elasticsearch
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - data_es_crypto_tracker:/usr/share/elasticsearch/data:rw
      - ./elasticsearch/plug-in/:/usr/share/elasticsearch/plug-in
      - ./elasticsearch/snapshot/:/usr/share/elasticsearch/snapshot
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch-node
      - path.repo=/usr/share/elasticsearch/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-service-network

  kibana:
    build: kibana/
    hostname: crypto-tracker_kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: crypto-tracker_kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - SERVER_NAME=kibana-node
    networks:
      - elastic-service-network

  app:
    build: app/
    hostname: crypto-tracker_app
    container_name: crypto-tracker_app
    depends_on:
      - elasticsearch
    restart: always
    networks:
      - elastic-service-network

# Networks to be created to facilitate communication between containers
networks:
  elastic-service-network:
    driver: bridge
    name: crypto-tracker-network

# Volumes
volumes:
  data_es_crypto_tracker:
    driver: local